"""Initial provenance and canonical draw schema (frozen revision)."""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

SCHEMA = """
CREATE TABLE sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    base_url TEXT NOT NULL,
    authority TEXT NOT NULL CHECK (authority IN ('operator','independent','manual')),
    access_policy TEXT
);
CREATE TABLE ingestion_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'running',
    configuration JSONB NOT NULL DEFAULT '{}',
    error_summary TEXT
);
CREATE TABLE raw_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES sources(id),
    run_id BIGINT NOT NULL REFERENCES ingestion_runs(id),
    url TEXT NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL,
    http_status INTEGER CHECK (http_status BETWEEN 100 AND 599),
    content_type TEXT,
    sha256 TEXT NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    body_path TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('valid','blocked','invalid','error')),
    parser_version TEXT
);
CREATE TABLE source_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT NOT NULL REFERENCES raw_artifacts(id),
    parser_version TEXT NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
);
CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
);
CREATE TABLE rule_regimes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id),
    code TEXT NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE,
    pool INTEGER NOT NULL CHECK (pool >= 7),
    main_count INTEGER NOT NULL DEFAULT 6 CHECK (main_count = 6),
    bonus_count INTEGER NOT NULL DEFAULT 1 CHECK (bonus_count = 1),
    schedule JSONB NOT NULL DEFAULT '[]',
    evidence_url TEXT,
    UNIQUE (game_id, code),
    UNIQUE (id, game_id),
    CHECK (ends_on IS NULL OR ends_on >= starts_on)
);
CREATE TABLE draws (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id),
    rule_id BIGINT NOT NULL,
    draw_date DATE NOT NULL,
    accepted_observation_id BIGINT REFERENCES source_observations(id),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','accepted','quarantined')),
    UNIQUE (game_id, draw_date),
    FOREIGN KEY (rule_id, game_id) REFERENCES rule_regimes(id, game_id),
    CHECK (status <> 'accepted' OR accepted_observation_id IS NOT NULL)
);
CREATE TABLE draw_numbers (
    draw_id BIGINT NOT NULL REFERENCES draws(id),
    number INTEGER NOT NULL CHECK (number > 0),
    role TEXT NOT NULL CHECK (role IN ('main','bonus')),
    physical_order INTEGER CHECK (physical_order > 0),
    PRIMARY KEY (draw_id, number)
);
CREATE TABLE prize_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_id BIGINT NOT NULL REFERENCES draws(id),
    tier TEXT NOT NULL,
    winners INTEGER CHECK (winners >= 0),
    prize_eur NUMERIC(18,2) CHECK (prize_eur >= 0),
    prize_as_published TEXT,
    prize_type TEXT,
    observation_id BIGINT REFERENCES source_observations(id),
    UNIQUE (draw_id, tier)
);
"""


def upgrade():
    for statement in SCHEMA.split(";"):
        if statement.strip():
            op.execute(statement)


def downgrade():
    for table in (
        "prize_tiers",
        "draw_numbers",
        "draws",
        "rule_regimes",
        "games",
        "source_observations",
        "raw_artifacts",
        "ingestion_runs",
        "sources",
    ):
        op.drop_table(table)
