"""Evidence-backed ingestion and complementary context."""

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None

DDL = """
ALTER TABLE raw_artifacts ADD COLUMN final_url TEXT;
ALTER TABLE raw_artifacts ADD CONSTRAINT artifact_identity UNIQUE(source_id,url,sha256);
ALTER TABLE source_observations ADD COLUMN record_key TEXT;
CREATE UNIQUE INDEX observation_identity ON source_observations(artifact_id,parser_version,record_key);
ALTER TABLE prize_tiers ADD COLUMN original_amount NUMERIC(18,2);
ALTER TABLE prize_tiers ADD COLUMN currency TEXT;
CREATE TABLE retrieval_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 artifact_id BIGINT NOT NULL REFERENCES raw_artifacts(id),
 run_id BIGINT NOT NULL REFERENCES ingestion_runs(id),
 retrieved_at TIMESTAMPTZ NOT NULL,
 UNIQUE(artifact_id,run_id,retrieved_at)
);
CREATE TABLE draw_context (
 draw_id BIGINT PRIMARY KEY REFERENCES draws(id),
 jackpot_amount NUMERIC(18,2), currency TEXT,
 outcome TEXT CHECK(outcome IN ('Won','Roll')),
 observation_id BIGINT NOT NULL REFERENCES source_observations(id),
 disputed BOOLEAN NOT NULL DEFAULT false,
 CHECK(jackpot_amount IS NULL OR jackpot_amount>=0)
);
CREATE TABLE quality_issues (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 observation_id BIGINT NOT NULL REFERENCES source_observations(id),
 draw_id BIGINT REFERENCES draws(id),
 kind TEXT NOT NULL, detail JSONB NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 resolved_at TIMESTAMPTZ, resolution_observation_id BIGINT REFERENCES source_observations(id),
 UNIQUE(observation_id,kind)
);
CREATE TABLE fetch_checkpoints (
 source_url TEXT PRIMARY KEY,
 artifact_id BIGINT NOT NULL REFERENCES raw_artifacts(id),
 run_id BIGINT NOT NULL REFERENCES ingestion_runs(id),
 status TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE rule_attributes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 record_key TEXT NOT NULL,
 artifact_id BIGINT NOT NULL REFERENCES raw_artifacts(id),
 payload JSONB NOT NULL, published_at TIMESTAMPTZ,
 UNIQUE(record_key,artifact_id)
);
CREATE TABLE calendar_dates (
 day DATE PRIMARY KEY,
 iso_year INTEGER NOT NULL, iso_week INTEGER NOT NULL, weekday INTEGER NOT NULL,
 scheduled BOOLEAN, observed BOOLEAN NOT NULL DEFAULT false,
 rule_id BIGINT REFERENCES rule_regimes(id)
);
CREATE TABLE calendar_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 record_key TEXT NOT NULL, artifact_id BIGINT NOT NULL REFERENCES raw_artifacts(id),
 payload JSONB NOT NULL, published_at TIMESTAMPTZ,
 UNIQUE(record_key,artifact_id)
);
CREATE TABLE winning_ticket_reports (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 record_key TEXT NOT NULL, artifact_id BIGINT NOT NULL REFERENCES raw_artifacts(id),
 payload JSONB NOT NULL, published_at TIMESTAMPTZ,
 UNIQUE(record_key,artifact_id)
);
CREATE TABLE official_period_metrics (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 record_key TEXT NOT NULL, artifact_id BIGINT NOT NULL REFERENCES raw_artifacts(id),
 payload JSONB NOT NULL, published_at TIMESTAMPTZ,
 UNIQUE(record_key,artifact_id)
);
"""


def upgrade():
    for statement in DDL.split(";"):
        if statement.strip():
            op.execute(statement)


def downgrade():
    for table in (
        "official_period_metrics",
        "winning_ticket_reports",
        "calendar_events",
        "calendar_dates",
        "rule_attributes",
        "fetch_checkpoints",
        "quality_issues",
        "draw_context",
        "retrieval_events",
    ):
        op.drop_table(table)
    op.execute(
        "ALTER TABLE prize_tiers DROP COLUMN currency, DROP COLUMN original_amount"
    )
    op.execute("DROP INDEX observation_identity")
    op.execute("ALTER TABLE source_observations DROP COLUMN record_key")
    op.execute(
        "ALTER TABLE raw_artifacts DROP CONSTRAINT artifact_identity, DROP COLUMN final_url"
    )
