"""Registry of verified, immutable audited dataset snapshots."""

from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None

STATEMENTS = (
    """CREATE TABLE dataset_snapshots (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 content_sha256 TEXT NOT NULL UNIQUE CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
 schema_version INTEGER NOT NULL CHECK (schema_version = 1),
 game TEXT NOT NULL,
 starts_on DATE NOT NULL,
 ends_on DATE NOT NULL,
 included_draws INTEGER NOT NULL CHECK (included_draws > 0),
 manifest_path TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 CHECK (ends_on >= starts_on)
)""",
    """CREATE FUNCTION reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME;
END $$""",
    """CREATE TRIGGER dataset_snapshots_immutable BEFORE UPDATE OR DELETE
 ON dataset_snapshots FOR EACH ROW EXECUTE FUNCTION reject_mutation()""",
)


def upgrade():
    for statement in STATEMENTS:
        op.execute(statement)


def downgrade():
    op.drop_table("dataset_snapshots")
    op.execute("DROP FUNCTION reject_mutation()")
