"""Prospective protocols, immutable pre-result issues and scored revisions."""

from alembic import op

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None

STATEMENTS = (
    """CREATE TABLE prospective_protocols (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 digest TEXT NOT NULL UNIQUE CHECK (digest ~ '^[0-9a-f]{64}$'),
 protocol JSONB NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
)""",
    """CREATE TABLE prospective_issues (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 protocol_id BIGINT NOT NULL REFERENCES prospective_protocols(id),
 arm TEXT NOT NULL,
 target_date DATE NOT NULL,
 status TEXT NOT NULL CHECK (status IN ('issued','missed','failed')),
 reason TEXT,
 deadline TIMESTAMPTZ NOT NULL,
 recorded_at TIMESTAMPTZ NOT NULL,
 cutoff_date DATE CHECK (cutoff_date IS NULL OR cutoff_date < target_date),
 CHECK (status <> 'issued' OR recorded_at < deadline),
 UNIQUE (protocol_id, arm, target_date)
)""",
    """CREATE TABLE prospective_lines (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 issue_id BIGINT NOT NULL REFERENCES prospective_issues(id),
 budget INTEGER NOT NULL CHECK (budget > 0),
 line_index INTEGER NOT NULL CHECK (line_index >= 0 AND line_index < budget),
 mains JSONB NOT NULL,
 seed NUMERIC(20,0),
 UNIQUE (issue_id, budget, line_index)
)""",
    """CREATE TABLE prospective_evaluations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 line_id BIGINT NOT NULL REFERENCES prospective_lines(id),
 result_evidence TEXT NOT NULL,
 revision INTEGER NOT NULL CHECK (revision > 0),
 outcome JSONB NOT NULL,
 matched_mains INTEGER NOT NULL CHECK (matched_mains BETWEEN 0 AND 6),
 hit_3_plus BOOLEAN NOT NULL,
 hit_5_plus BOOLEAN NOT NULL,
 evaluated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE (line_id, result_evidence),
 UNIQUE (line_id, revision)
)""",
    *(
        f"""CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table}
 FOR EACH ROW EXECUTE FUNCTION reject_mutation()"""
        for table in (
            "prospective_protocols",
            "prospective_issues",
            "prospective_lines",
            "prospective_evaluations",
        )
    ),
)


def upgrade():
    for statement in STATEMENTS:
        op.execute(statement)


def downgrade():
    for table in (
        "prospective_evaluations",
        "prospective_lines",
        "prospective_issues",
        "prospective_protocols",
    ):
        op.drop_table(table)
